import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "./fonts";
import { ToastProvider } from "@/components/ui/Toast";

export const metadata: Metadata = {
  title: "Seolstudy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.variable}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
